### ISSUE TITLE
is_dockerized

### ISSUE THREAD

**Issue by jayvdb** [night-crawler/django-docker-helpers#5]
`is_dockerized` currently reads `DOCKERIZED`.

Is that enough?  Shouldnt it use https://github.com/night-crawler/docker-check ?

**Comment by jayvdb** [comment]
@night-crawler , could I get access to docker-check on PyPI as I would like to get that released , in order to use it here.

**Comment by night-crawler** [comment]
@jayvdb, check your access, please. 

BTW, I rather think that making an application aware of the fact that it's running inside a container and taking into account this information somewhere in business logic is a marker of poor design. 
(I mean, I added it previously because I needed a hack)

**Comment by jayvdb** [comment]
Got access.  Thanks.

And I agree with you.  I dont need it in any business logic.  I need it in my `settings.py`, and other bootstrap code which allows developers to quick spin up the system inside or outside of docker, and we have multiple profiles within docker-compose for different testing needs.

Basically, I need hacks too :P
